dist: xenial

language: python
python:
    - 3.7

addons:
  apt:
    update: true

before_install:
    - sudo apt-get install python3-dev g++ make
    - pip install -U -r requirements.txt
    - git clone --depth 1 https://github.com/inventree/inventree ./inventree_server
    - cd inventree_server && make install && cd ..
    - cp ./test/inventree_config.yaml ./inventree_server/InvenTree/config.yaml
    - cd inventree_server && make migrate && cd ..
    - cd inventree_server/InvenTree
    - python manage.py loaddata ../../test/test_data.json
    # Run a development server in the background...
    - python manage.py runserver 127.0.0.1:8000 &

script:
    # Install inventree to system python
    - pip install wheel
    - python setup.py sdist bdist_wheel
    - pip install dist/inventree-*.tar.gz
    # Run unit tests
    - coverage run test/test_api.py
    - flake8 .

after_success:
    coveralls